name: my first action
on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "welcome"
        - name: list files
          run: ls
        - name: display content
          run: cat README.md