name: my first action
on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: co repo
          uses: actions/checkout@v4

        - name: welcome message
          run: | 
            echo "welcome"
            ls -lart
            cat README.md

        - name: generate ASCII
          run: cowsay -f dragon "run for cover, I'm dragon... GRRR" >> dragon.txt