name: generate ascci
on: 
  push
jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: co repo
              uses: actions/checkout@v4

            - name: list file
              run: ls -lart
            - name: execute script
              run: |
                chmod +x generate-ascii.sh
                ./generate-ascii.sh
